name: test

on:
  pull_request:
    types: [opened, synchronize]

  push:
    branches: [main]

  workflow_dispatch:

jobs:
  install:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure Git
        uses: Homebrew/actions/git-user-config@master

      # This action automatically installs the locally checked out tap.
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        id: gems-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.gems-cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Install CLI
        run: |
          brew install databricks

      - name: Run CLI
        run: |
          databricks version
